POST https://node-exercice.onrender.com/videos
Content-Type: application/json

{
    "title": "video node",
    "description": "like this video 01",
    "duration": 180
}

###

GET https://node-exercice.onrender.com/videos?search=node
# Use o ?search=node apos videos para procurar 

### 

PUT https://node-exercice.onrender.com/videos/d38546d8-ab13-4632-9ccb-d430d35904f4
Content-Type: application/json

{
    "title": "video node 02",
    "description": "like this video node 02",
    "duration": 180
}

###

DELETE https://node-exercice.onrender.com/videos/d38546d8-ab13-4632-9ccb-d430d35904f4